language: c

os:
    - linux
    - osx

sudo: required
dist: trusty

before_install:
    - if [ `uname` = "Linux" ]; then
          sudo apt-get update -qq;
          sudo apt-get install -y build-essential debhelper librtlsdr-dev libusb-1.0-0-dev pkg-config;
      elif [ `uname` = "Darwin" ]; then
          brew update;
          brew install -v librtlsdr;
      fi

script:
    - if [ `uname` = "Linux" ]; then
          dpkg-buildpackage -b -us -uc;
      elif [ `uname` = "Darwin" ]; then
          make;
         make test;
      fi
